language: generic
dist: xenial
sudo: false

env:
  global:
  - KUBECTL_VERSION=1.10.3
  - HELM_VERSION=2.12.2
  - HELM_DIFF_PLUGIN_VERSION=v2.11.0+3
  - secure: VfW9uVdmMBwwOsOmZ4D5NuDNv8F8F02u7vLybBeoi0RB2hq6tt3Br0AZWPmS5gskESB7HxWD6FaTrY0Qq9VhGMzIdty9VQoQ5jtQj2zXPg+LXRzKXF1yYNjeNy7tvdQGhYebrP/vcv1y6CTMZCs6MlY4kHwhimx56w6vvYYuJIlAR+YA9mSZsK5HsH5BBRbz89yIRkkLk3RlTssu5alSOzPhT+Ol1kJUC6v4EU+tvZT8sBCOjjKEbtZHqOoaLSP8TWXz/lSElxqsujK7GhmnsIgbCT4vhSHTwN0dHCtcBesLotzC8IepMIF7uvEmC8RI6FY2ohPbJAk9e1f7ltgtzic2OjAr0bQqiGqlLVFlX2HgUkgcfKho8uNANJBCXgdvgxEhLnObc0l0W85LEDKbTak7bRYTyeDc7Pe6yCgzRBvEKAuxrj0LmzstKHQ7ehQrA2TXil2C68ZSdUYsn0V1vuN/jaODMsO17L4d2Ab7Am53rEuUWTUG+xAYijaxP8xCWiBuGtWAH+NWV2grW3eslsrNRuN1y1QYDIoLLn7EQQ1cQq0gRpngp/74qPCGKlGgn1Hy48TsOn3sDUgLR9IjhkmjjA+PVXE2zLJE6a/uoEac1LVM5K0PNVs432LZhZ5vuqL3nHDeeG1A2bBsf+HZegCRUC3C7Mx43g1Yic2ozcY=

install: .travis/install.sh

script: PATH=$(pwd)/bin/:$PATH .travis/test.sh

deploy:
  provider: script
  skip_cleanup: true
  script: PATH=$(pwd)/bin/:$PATH .travis/deploy.sh
  on:
    branch: master
