settings:
  # Name of the service account within each namespace that should be used for tiller
  serviceAccount: "tiller"

namespaces:
  kube-system:
  elad:
    protected: false
    installTiller: true
    labels:
      env: "elad"

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  incubator: "http://storage.googleapis.com/kubernetes-charts-incubator"
  ethersphere: "https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/"

apps:
  # Private cluster
  private-swarm:
    tillerNamespace: "elad"
    namespace: "elad"
    name: "swarm-private"
    enabled: true
    chart: "ethersphere/swarm-private"
    #chart: "/home/nonsense/code/helm-charts/artifacts/swarm-private-0.0.2.tgz"
    version: "0.0.2"
    description: "(Private) Swarm elad cluster"
    valuesFiles:
      - "local/swarm.yaml"
      - "local/version.yaml"
    set:
      swarm.replicaCount: "$REPLICA_COUNT"
    wait: true
    timeout: 600
  #private-smoke-a:
    #tillerNamespace: "elad"
    #namespace: "elad"
    #name: "private-smoke-a"
    #enabled: true
    #chart: "ethersphere/smoke"
    #version: "0.0.2"
    #description: "(Private) Smoke test: Upload and sync"
    #valuesFiles:
      #- "elad/private-smoke-a.yaml"
      #- "elad/version.yaml"
    #set:
      #smoke.config.swarmReplicas: "$REPLICA_COUNT"
    #wait: false
