settings:
  # Name of the service account within each namespace that should be used for tiller
  serviceAccount: "tiller"

namespaces:
  kube-system:
  staging:
    protected: false
    installTiller: true
    labels:
      env: "staging"
    limits:
      default:
        cpu: "300m"
        memory: "300Mi"
      defaultRequest:
        cpu: "300m"
        memory: "300Mi"

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  incubator: "http://storage.googleapis.com/kubernetes-charts-incubator"
  ethersphere: "https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/"

apps:
  # Public cluster
  public-swarm:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "swarm-public"
    enabled: false
    purge: true
    chart: "ethersphere/swarm"
    version: "0.0.2"
    description: "(Public) Swarm staging cluster"
    valuesFiles:
      - "staging/public-swarm.yaml"
      - "common/swarm-version.yaml"
    set:
      swarm.replicaCount: "$STAGING_PUBLIC_REPLICAS"
    wait: true
    timeout: 600
  public-smoke-50:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "public-smoke-50"
    enabled: false
    purge: true
    chart: "ethersphere/smoke"
    version: "0.0.2"
    description: "(Public) Smoke test: Upload and sync 50KB"
    valuesFile: "staging/public-smoke-50.yaml"
    set:
      smoke.config.swarmReplicas: "$STAGING_PUBLIC_REPLICAS"
    wait: false
  public-smoke-110:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "public-smoke-110"
    enabled: false
    purge: true
    chart: "ethersphere/smoke"
    version: "0.0.2"
    description: "(Public) Smoke test: Upload and sync 110KB"
    valuesFile: "staging/public-smoke-110.yaml"
    set:
      smoke.config.swarmReplicas: "$STAGING_PUBLIC_REPLICAS"
    wait: false
