settings:
  # Name of the service account within each namespace that should be used for tiller
  serviceAccount: "tiller"

namespaces:
  kube-system:
  staging:
    protected: false
    installTiller: true
    labels:
      env: "staging"

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  incubator: "http://storage.googleapis.com/kubernetes-charts-incubator"
  ethersphere: "https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/"

apps:
  # Public cluster
  public-swarm:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "swarm-public"
    enabled: true
    chart: "ethersphere/swarm"
    version: "0.0.2"
    description: "(Public) Swarm staging cluster"
    valuesFiles:
      - "staging/public-swarm.yaml"
      - "staging/swarm-version.yaml"
    set:
      swarm.replicaCount: "$STAGING_PUBLIC_REPLICAS"
    wait: true
    timeout: 600
  public-smoke-50:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "public-smoke-50"
    enabled: true
    chart: "ethersphere/smoke"
    version: "0.0.2"
    description: "(Public) Smoke test: Upload and sync 50KB"
    valuesFile: "staging/public-smoke-50.yaml"
    set:
      smoke.config.swarmReplicas: "$STAGING_PUBLIC_REPLICAS"
    wait: false
  public-smoke-110:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "public-smoke-110"
    enabled: true
    chart: "ethersphere/smoke"
    version: "0.0.2"
    description: "(Public) Smoke test: Upload and sync 110KB"
    valuesFile: "staging/public-smoke-110.yaml"
    set:
      smoke.config.swarmReplicas: "$STAGING_PUBLIC_REPLICAS"
    wait: false
  # Private cluster
  private-swarm:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "swarm-private"
    enabled: true
    chart: "ethersphere/swarm-private"
    version: "0.0.2"
    description: "(Private) Swarm staging cluster"
    valuesFiles:
      - "staging/private-swarm.yaml"
      - "staging/swarm-version.yaml"
      - "staging/swarm-bootnode-version.yaml"
    set:
      swarm.replicaCount: "$STAGING_PRIVATE_REPLICAS"
    wait: true
    timeout: 600
  private-smoke-50:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "private-smoke-50"
    enabled: true
    chart: "ethersphere/smoke"
    version: "0.0.2"
    description: "(Private) Smoke test: Upload and sync 50KB"
    valuesFile: "staging/private-smoke-50.yaml"
    set:
      smoke.config.swarmReplicas: "$STAGING_PRIVATE_REPLICAS"
    wait: false
  private-smoke-110:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "private-smoke-110"
    enabled: true
    chart: "ethersphere/smoke"
    version: "0.0.2"
    description: "(Private) Smoke test: Upload and sync 110KB"
    valuesFile: "staging/private-smoke-110.yaml"
    set:
      smoke.config.swarmReplicas: "$STAGING_PRIVATE_REPLICAS"
    wait: false
  # Private cluster with global-store
  private-global-store:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "swarm-private-global-store"
    enabled: true
    chart: "ethersphere/swarm-global-store"
    version: "0.0.1"
    description: "(Private) Swarm global store"
    valuesFiles:
      - "staging/private-global-store.yaml"
    wait: true
    priority: -3
  private-swarm-gs:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "swarm-private-gs"
    enabled: true
    chart: "ethersphere/swarm-private"
    version: "0.0.2"
    description: "(Private) Swarm staging cluster using global-store"
    valuesFiles:
      - "staging/private-swarm-gs.yaml"
      - "staging/swarm-version.yaml"
      - "staging/swarm-bootnode-version.yaml"
    set:
      swarm.replicaCount: "$STAGING_PRIVATE_GS_REPLICAS"
    wait: true
    timeout: 600
  private-smoke-gs-110:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "private-smoke-gs-110"
    enabled: true
    chart: "ethersphere/smoke"
    version: "0.0.2"
    description: "(Private) Smoke test: Upload and sync 110KB"
    valuesFile: "staging/private-smoke-gs-110.yaml"
    set:
      smoke.config.swarmReplicas: "$STAGING_PRIVATE_GS_REPLICAS"
    wait: false
