settings:
  # Name of the service account within each namespace that should be used for tiller
  serviceAccount: "tiller"

namespaces:
  kube-system:
  staging:
    protected: false
    installTiller: true
    labels:
      env: "staging"
    limits:
      default:
        cpu: "300m"
        memory: "300Mi"
      defaultRequest:
        cpu: "300m"
        memory: "300Mi"

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  incubator: "http://storage.googleapis.com/kubernetes-charts-incubator"
  ethersphere: "https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/"

apps:
  # Public cluster
  public-swarm:
    tillerNamespace: "staging"
    namespace: "staging"
    name: "swarm-public"
    enabled: true
    purge: true
    chart: "ethersphere/swarm"
    version: "0.0.5"
    description: "(Public) Swarm staging cluster"
    valuesFiles:
      - "staging/public-swarm.yaml"
      - "common/swarm-version.yaml"
      - "common/swarm-bootnode-version.yaml"
    set:
      swarm.replicaCount: "$STAGING_PUBLIC_REPLICAS"
    wait: true
    timeout: 600
