settings:
  # Name of the service account within each namespace that should be used for tiller
  serviceAccount: "tiller"

namespaces:
  kube-system:
  janos4:
    protected: false
    installTiller: true
    labels:
      env: "janos4"

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  incubator: "http://storage.googleapis.com/kubernetes-charts-incubator"
  ethersphere: "https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/"

apps:
  # Private cluster
  private-swarm:
    tillerNamespace: "janos4"
    namespace: "janos4"
    name: "swarm-private"
    enabled: true
    chart: "ethersphere/swarm-private"
    version: "0.0.5"
    description: "(Private) Swarm cluster"
    valuesFiles:
      - "swarm.yaml"
    set:
      swarm.replicaCount: "$REPLICAS"
    wait: true
    timeout: 2400
  private-smoke-a:
    tillerNamespace: "janos4"
    namespace: "janos4"
    name: "private-smoke-a"
    enabled: true
    chart: "ethersphere/smoke"
    version: "0.0.2"
    description: "(Private) Smoke test: Upload and sync"
    valuesFiles:
      - "smoke.yaml"
    set:
      smoke.config.swarmReplicas: "$REPLICAS"
    wait: false
